# Ejercicios de NumPy

- Importa la librería de NumPy.

In [1]:
import numpy as np

- Crea un array de 1 dimension y 10 elementos.

In [2]:
array1_dim = np.random.randint(1, 50, size=10)
array1_dim

array([ 9,  5,  7, 34, 25, 19, 32, 31, 18,  7])

In [3]:
array1_dim.ndim

1

- Reemplaza todos los números impares por el valor "par" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [4]:
array_par = np.empty_like(array1_dim, dtype=object)

for i in range(10):
    if array1_dim[i] % 2 == 0:
        array_par[i]= "par"
    else:
        array_par[i]= "impar"

array_par

array(['impar', 'impar', 'impar', 'par', 'impar', 'impar', 'par', 'impar',
       'par', 'impar'], dtype=object)

- Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [5]:
array_cambio_forma = np.reshape(array_par, (2,5))
array_cambio_forma

array([['impar', 'impar', 'impar', 'par', 'impar'],
       ['impar', 'par', 'impar', 'par', 'impar']], dtype=object)

- Extrae los elementos comunes de los siguientes arrays

- array1 = np.array([1,2,3,2,3,4,3,4,5,6])
 
- array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [6]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [7]:
np.intersect1d(array1, array2)

array([2, 4])

- Extraed los elementos que están en el array1 pero no en el array2.

In [8]:
np.setdiff1d(array1, array2)

array([1, 3, 5, 6])

- Extraed las posiciones donde tengamos elementos que sean iguales.

In [9]:
np.intersect1d(array1, array2, return_indices=True)

(array([2, 4]), array([1, 5], dtype=int64), array([1, 5], dtype=int64))

- Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [10]:
array10_40 = np.random.randint(0, 50, (3,5))
array10_40

array([[ 1, 45,  2, 23, 19],
       [16, 46, 29, 19,  8],
       [15,  2, 21, 27, 39]])

In [11]:
extraccion = array10_40[np.where((array10_40 < 10 ) | (array10_40 > 40))]
extraccion
# al no mencionar si teniamos que crear otro array como en el ejercicio 3, decidí usar el metodo np.where y el operador or (|).

array([ 1, 45,  2, 46,  8,  2])

- Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [12]:
array_decimal = np.random.uniform(5, 10, size=(5,3))
array_decimal

array([[9.79087025, 5.30515948, 7.54155485],
       [8.81478395, 5.21137356, 7.40448227],
       [8.06455204, 7.38518456, 6.75318311],
       [6.87969695, 6.44824098, 9.61198223],
       [7.25207738, 9.27216631, 8.81284099]])

- Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20

In [13]:
array_3d = np.random.randint(1, 20, (2,4,7))
array_3d

array([[[ 7, 19,  1,  6,  8,  3,  7],
        [ 7, 12,  5, 10, 13,  2,  1],
        [15, 16,  4,  7,  4, 10, 11],
        [12, 13,  5,  4,  1, 11, 15]],

       [[ 7, 14,  2, 19,  4,  2,  4],
        [13, 12, 16, 17, 19,  3, 16],
        [ 4, 18,  6, 12,  6, 10,  3],
        [10, 16,  8, 19, 19,  1, 12]]])

In [14]:
array_3d.ndim

3

- Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [15]:
np.transpose(array_3d, (1,2,0))

array([[[ 7,  7],
        [19, 14],
        [ 1,  2],
        [ 6, 19],
        [ 8,  4],
        [ 3,  2],
        [ 7,  4]],

       [[ 7, 13],
        [12, 12],
        [ 5, 16],
        [10, 17],
        [13, 19],
        [ 2,  3],
        [ 1, 16]],

       [[15,  4],
        [16, 18],
        [ 4,  6],
        [ 7, 12],
        [ 4,  6],
        [10, 10],
        [11,  3]],

       [[12, 10],
        [13, 16],
        [ 5,  8],
        [ 4, 19],
        [ 1, 19],
        [11,  1],
        [15, 12]]])